### ISSUE TITLE
配置文件中，包含明文密码？

### ISSUE THREAD

**Issue by triumph** [megaease/easeprobe#178]
大大好，不到24小时就上线，2个需求， 再次感谢。
我有个建议，不知道好不好啊， 就是在配置中我发现很多需要配置明文的密码。 我们能不能加密一下，比如base64， 
或者是先提供一个自定义加密密码的命令， 比如   ./bin/easeprobe  -a  "加密key“    password   >  加密后的密码，
把加密后的密码写入配置文件， 然后启动的时候，带上一个 加密key，用于解密 ，   运行比如   ./bin/easeprobe -k ”加密key“

这样 别看看到了配置文件， 也不会知道 生产服务的各个密码。

**Comment by haoel** [comment]
At first, base64 is not encryption, it is just an encoding method. it's the same as plain text.

Secondly, using a private key to do the encryption work is good, but you still need to bring this private key into the production, everyone can use `ps` command to get the private key because it is on the command line. So everyone knows this private key can decrypt the sensitive message. 

one of the best practices is that uses an environment variable to replace the plain text in the configuration file. This is already supported in EaseProbe.

You can replace the password with an environment variable. we support this feature.  pls check PR#37

**Comment by triumph** [comment]
懂了， 感谢

**Comment by haoel** [comment]
close this issue, feel free open it if you have further questions.
