### ISSUE TITLE
Can you add a Feature like cURL's "--resolve" option to pin a request to an IP address

### ISSUE THREAD

**Issue by feeops** [megaease/easeprobe#203]
**Background & X Problem**
If one domain has different cdn suppliers.
I want to check all supplier ssl cert.

**Proposal and Expectation**

**Solutions & Y Problems**
cURL's "--resolve" option is ok
https://stackoverflow.com/questions/40624248/golang-force-http-request-to-specific-ip-similar-to-curl-resolve

**Additional context**
Use cURL's "--resolve" option to pin a request to an IP address
https://support-acquia.force.com/s/article/360005257154-Use-cURL-s-resolve-option-to-pin-a-request-to-an-IP-address

**Comment by haoel** [comment]
@feeops, thanks to raise this issue.

I'd like to understand more. 

if you've already known the real IP address, why not just configure that IP into config.yaml file?

**Comment by feeops** [comment]
> 

Some web server will block request of IP.
Some CDN supplier  will change their server's IP.

**Comment by proditis** [comment]
> if you've already known the real IP address, why not just configure that IP into config.yaml file?

After thinking about this I dont think its a viable alternative to what the OP has requested. 

Some extra thoughts
* We cannot use IP as main source since using it changes the entire `GET` request performed and thus might cause the SSL validation to fail (as the IP does not much the certificate CN and we will (?) receive an error), SNI negotiation will also fail with using IP and Host headers.
* Hardened systems that only serve content for specific HOST entries, will fail if we use the IP (ie my webserver does not accept requests for IP or non defined domains)
* The IP based request does not "resolve" redirects, ie we get a `302 Location: https://somedomain.com`, with this option we can instruct the probe to always resolve domain `somedomain.com` to the given IP and follow the redirect on the server of our choosing
* This can be very useful for testing servers behind a CDN, since the IP of the backend server does not match the public DNS one, so we can use this to connect to given IP's and perform the HTTP checks, emulating a request as if it was received from the CDN proxies

I hope these help illustrate a few more use cases where this feature could be useful :smiley_cat:
