### ISSUE TITLE
Does easeprobe supports schedule in every minute?

### ISSUE THREAD

**Issue by EasonAssassin** [megaease/easeprobe#219]
Currently, the schedule only supports daily, weekly (Sunday), monthly (Last Day), none.
If this schedule can set minutely, meas easeprobe can support Real-time monitoring.

**Comment by haoel** [comment]
do you mean the SLA report?  I‘d like to understand the reason why you want it every minute.

**Comment by EasonAssassin** [comment]
> do you mean the SLA report? I‘d like to understand the reason why you want it every minute. And what does the 'real-time monitoring' mean?

I'd like to set a standard to alert by dingding or other notifications. For example, if the google website returns 500, easeprobe will send alerts. Schedule in every minute give us timely feedback. I beleive if easeprobe supports this function, easeprobe will be more popular.
Just personal opinion! 😉

**Comment by haoel** [comment]
OK, I see. you want the level trigger instead of the edge trigger, currently, the EaseProbe only supports the edge trigger.  In practice, the level trigger is quite annoying, that's why most probe monitoring software use the edge trigger.  but I am open to supporting the level trigger and different customers can have different choices. 

You are welcome to contribute a PR to do this.

And I still don't understand what you mean by "Schedule in every minute"? do you mean probe every minute? or send the SLA report every minute?

**Comment by EasonAssassin** [comment]
Thanks. I'd like to contribute a PR to do this. I mean  probe every minute but SLA report sent by some standards. Only send the SLA report(dingding alerts e.g.) when services reach the standard. For example, if http probe returns 500, SLA report will be sent.

**Comment by haoel** [comment]
> Only send the SLA report(dingding alerts e.g.) when services reach the standard. For example, if http probe returns 500, SLA report will be sent.

may I know why? what's the purpose of this? SLA is a kind of report, the report is a kind of statistics, and it should be sent within the same period, otherwise, how can we know if the SLA getting better or worse?

**Comment by haoel** [comment]
@EasonAssassin I close this issue as there hasn't response. please feel free open it if you have further ideas.

**Comment by haoel** [comment]
PR#236 addresses this issued
