### ISSUE TITLE
Add  default config.yaml to Docker Image

### ISSUE THREAD

**Issue by zhoukangcn** [megaease/easeprobe#229]
**Background & X Problem**
When I follow the readme to run docker, it fails to start as follow
```
Using config file: /opt/config.yaml
ERRO[0000] error: stat config.yaml: no such file or directory
ERRO[0000] Fatal: Cannot read the YAML configuration file!
```
I think we can add a default configuration file to Docker Image, and make docker st

**Proposal and Expectation**
Simplification startup process when using docker

**Solutions & Y Problems**
add a default configurate file to Docker Image

**Additional context**
N/A

**Comment by haoel** [comment]
I think adding the default `config.yaml` is meaningless because we don't know what default probe and notification we need to configure. we only can configure some dummy probers or notifiers, this is really meaningless.

So, I think reporting the error to ask the user to supply a configuration file is the right way.
