### ISSUE TITLE
how to custom dingtalk message template?

### ISSUE THREAD

**Issue by whisper-bye** [megaease/easeprobe#348]
**Background & X Problem**
As above

**Proposal and Expectation**
at @ group member or custom the msg contents

**Comment by haoel** [comment]
at this moment you cannot do this! could you please descript what information you want to put into the contents?

**Comment by whisper-bye** [comment]
each service is assigned a specified operations staff to notify a specific member

like this
serviceA @member1
serviceB @member2 @member3
etc.

**Comment by haoel** [comment]
I think we cannot meet this requirement by using a customized message.  The major reason is we need to know which service is and add the different mentions - the business logic is hard to be solved by message template.

I suggest solving this by using the [channel](https://github.com/megaease/easeprobe/blob/main/docs/Manual.md#4-channel) feature. The reasons as below:

- This is a typical Pub/Sub concept -  different people subscribe to different topics.
-  A good design won't couple with the real person, because people would come or leave. A good design would abstract it by using a group or a team concept.
- Putting all of the messages in the same group is not a good practice, you should separate them into different categories.  

So, I think you can use the `channel` to send notifications to different groups, and people just subscribe to the group if they are interested.

**Comment by whisper-bye** [comment]
Thank you. That makes sense
